"""RotorHazard integration for the Local Voice plugin."""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from filtermanager import Flt
from RHUI import UIField, UIFieldSelectOption, UIFieldType

from .const import (
    CONFIG_SECTION,
    DEFAULT_MODEL,
    DEFAULT_SPEED,
    DEFAULT_TEST_PHRASE,
    ENABLE_OPTION,
    PANEL_ID,
    SPEECH_SPEED_OPTION,
    TEST_PHRASE_OPTION,
    VOICE_MODEL_OPTION,
    VOICE_MODELS,
)
from .piper import PiperSynthesizer, SynthesisResult

logger = logging.getLogger(__name__)


class LocalVoicePlugin:
    """RotorHazard plugin for local Piper TTS generation and WAV caching."""

    def __init__(self, rhapi: Any) -> None:
        """Initialize the plugin and register RotorHazard integration points."""
        self._rhapi = rhapi
        data_dir = Path(
            getattr(self._rhapi.server, "data_dir", Path.home() / "rh-data")
        )
        cache_root = data_dir / "local_voice_cache"
        self._tts = PiperSynthesizer(
            model_dir=cache_root / "models",
            tts_dir=cache_root / "tts",
            set_status=self._set_status,
        )

        self._register_ui()
        self._register_filters()
        logger.info("Local Voice plugin initialized")

    def _register_ui(self) -> None:
        """Register settings panel, options, status fields, and quick buttons."""
        self._rhapi.config.register_section(CONFIG_SECTION)
        self._rhapi.ui.register_panel(PANEL_ID, "Local Voice", "settings", open=False)
        self._rhapi.fields.register_option(
            UIField(
                ENABLE_OPTION,
                "Enable plugin audio",
                UIFieldType.CHECKBOX,
                value=False,
                desc="Generate server-side local voice callout WAV files.",
                persistent_section=CONFIG_SECTION,
            ),
            panel=PANEL_ID,
        )
        self._rhapi.fields.register_option(
            UIField(
                VOICE_MODEL_OPTION,
                "Voice model",
                UIFieldType.SELECT,
                value=DEFAULT_MODEL,
                options=[
                    UIFieldSelectOption(model_name, model["label"])
                    for model_name, model in VOICE_MODELS.items()
                ],
                desc="Downloaded once into the local RotorHazard data cache.",
                persistent_section=CONFIG_SECTION,
            ),
            panel=PANEL_ID,
        )
        self._rhapi.fields.register_option(
            UIField(
                SPEECH_SPEED_OPTION,
                "Speech speed",
                UIFieldType.NUMBER,
                value=DEFAULT_SPEED,
                desc=(
                    "Piper length scale. Currently part of the cache key; "
                    "synthesis uses the model default."
                ),
                html_attributes={"min": "0.5", "max": "2.0", "step": "0.1"},
                persistent_section=CONFIG_SECTION,
            ),
            panel=PANEL_ID,
        )
        self._rhapi.fields.register_option(
            UIField(
                TEST_PHRASE_OPTION,
                "Test phrase",
                UIFieldType.TEXT,
                value=DEFAULT_TEST_PHRASE,
                desc="Phrase generated by the test button.",
                persistent_section=CONFIG_SECTION,
            ),
            panel=PANEL_ID,
        )
        self._rhapi.ui.register_markdown(
            PANEL_ID,
            "local_voice_duplicate_prevention",
            (
                "Duplicate prevention: set Voice Volume to 0 on regular "
                "RotorHazard browser clients while this plugin is active."
            ),
        )
        self._rhapi.ui.register_quickbutton(
            panel=PANEL_ID,
            name="local_voice_test_phrase",
            label="Generate test phrase",
            function=self.generate_test_phrase,
        )

    def _register_filters(self) -> None:
        """Register RotorHazard filter hooks used by the plugin."""
        self._rhapi.filters.add(
            Flt.EMIT_PHONETIC_TEXT,
            "local_voice_log_phonetic_text",
            self.log_phonetic_text,
        )

    def generate_test_phrase(self, _args: dict[str, Any] | None = None) -> None:
        """Generate the configured test phrase and report the result in the UI."""
        text = str(self._option(TEST_PHRASE_OPTION, DEFAULT_TEST_PHRASE)).strip()
        if not text:
            text = DEFAULT_TEST_PHRASE

        wav_path = self.synthesize_to_cache(text)
        if wav_path is None:
            self._rhapi.ui.message_alert(f"Local Voice test failed: {self._status}")
            return

        self._rhapi.ui.message_notify(f"Local Voice test WAV ready: {wav_path.name}")

    def log_phonetic_text(self, payload: dict[str, Any]) -> dict[str, Any]:
        """Log server-originated phonetic text while leaving payload unchanged."""
        text = payload.get("text") if isinstance(payload, dict) else None
        if isinstance(text, str) and text.strip():
            logger.info("Local Voice intercepted phonetic text: %s", text)
        return payload

    def synthesize_to_cache(self, text: str) -> Path | None:
        """Return a cached WAV path for text, synthesizing it with Piper if needed."""
        result = self._tts.synthesize_to_cache(
            text=text,
            model_name=self._model_name(),
            speed=self._speed_value(),
        )
        if result is None:
            return None

        self._record_generation(result)
        return result.wav_path

    def _record_generation(self, result: SynthesisResult) -> None:
        """Log metadata for the last generated phrase."""
        source = "cache hit" if result.cache_hit else "synthesized"
        size = result.wav_path.stat().st_size if result.wav_path.exists() else 0
        name = result.wav_path.name
        ms = result.duration_ms
        self._set_status(f"Ready ({source}): {name} | {size} bytes | {ms} ms")

    def _set_status(self, status: str) -> None:
        """Log a status change."""
        logger.info("Local Voice status: %s", status)

    def _model_name(self) -> str:
        """Return the configured model name or the default."""
        value = str(self._option(VOICE_MODEL_OPTION, DEFAULT_MODEL))
        return value if value in VOICE_MODELS else DEFAULT_MODEL

    def _speed_value(self) -> str:
        """Return normalized speech speed text for cache-key stability."""
        value = self._option(SPEECH_SPEED_OPTION, DEFAULT_SPEED)
        try:
            return f"{float(value):.2f}"
        except (TypeError, ValueError):
            return f"{float(DEFAULT_SPEED):.2f}"

    def _option(self, name: str, default: Any) -> Any:
        """Read a RotorHazard option and fall back when it is unset."""
        value = self._rhapi.db.option(name)
        return default if value is None else value

