"""UI panel, options, and quick-buttons registration for Local Voice."""

from __future__ import annotations

from typing import Any

from RHUI import UIField, UIFieldSelectOption, UIFieldType

from .const import (
    CONFIG_SECTION,
    DEFAULT_MODEL,
    DEFAULT_SPEED,
    DEFAULT_TEST_PHRASE,
    ENABLE_CROSSING_BEEPS_OPTION,
    ENABLE_OPTION,
    PANEL_ID,
    SPEECH_SPEED_OPTION,
    TEST_PHRASE_OPTION,
    VOICE_MODEL_OPTION,
    VOICE_MODELS,
)


def register_ui(
    rhapi: Any,
    test_callback: Any,
    clear_cache_callback: Any,
) -> None:
    """Register the Local Voice settings panel, options, and quick buttons."""
    rhapi.config.register_section(CONFIG_SECTION)
    rhapi.ui.register_panel(PANEL_ID, "Local Voice", "settings", open=False)

    # Main enable
    rhapi.fields.register_option(
        UIField(
            ENABLE_OPTION,
            "Enable plugin audio",
            UIFieldType.CHECKBOX,
            value=False,
            desc="Generate server-side local voice callout WAV files.",
            persistent_section=CONFIG_SECTION,
        ),
        panel=PANEL_ID,
    )

    # Voice model + speed
    rhapi.fields.register_option(
        UIField(
            VOICE_MODEL_OPTION,
            "Voice model",
            UIFieldType.SELECT,
            value=DEFAULT_MODEL,
            options=[
                UIFieldSelectOption(model_name, model["label"])
                for model_name, model in VOICE_MODELS.items()
            ],
            desc="Downloaded once into the local RotorHazard data cache.",
            persistent_section=CONFIG_SECTION,
        ),
        panel=PANEL_ID,
    )
    rhapi.fields.register_option(
        UIField(
            SPEECH_SPEED_OPTION,
            "Speech speed",
            UIFieldType.NUMBER,
            value=DEFAULT_SPEED,
            desc="Playback speed (0.5 = slow, 1.0 = normal, 2.0 = fast).",
            html_attributes={"min": "0.5", "max": "2.0", "step": "0.1"},
            persistent_section=CONFIG_SECTION,
        ),
        panel=PANEL_ID,
    )

    # Crossing beeps
    rhapi.fields.register_option(
        UIField(
            ENABLE_CROSSING_BEEPS_OPTION,
            "Crossing enter / exit beeps",
            UIFieldType.CHECKBOX,
            value=False,
            persistent_section=CONFIG_SECTION,
        ),
        panel=PANEL_ID,
    )

    # Warnings
    rhapi.ui.register_markdown(
        PANEL_ID,
        "local_voice_dup_voice",
        "⚠ Set Voice Volume to 0 on all browser clients.",
    )
    rhapi.ui.register_markdown(
        PANEL_ID,
        "local_voice_dup_beeps",
        "⚠ Disable browser beeps on all clients if crossing beeps are enabled.",
    )

    # Test phrase
    rhapi.fields.register_option(
        UIField(
            TEST_PHRASE_OPTION,
            "Test phrase",
            UIFieldType.TEXT,
            value=DEFAULT_TEST_PHRASE,
            desc="Phrase generated by the test button.",
            persistent_section=CONFIG_SECTION,
        ),
        panel=PANEL_ID,
    )
    rhapi.ui.register_quickbutton(
        panel=PANEL_ID,
        name="local_voice_test_phrase",
        label="Generate test phrase",
        function=test_callback,
    )
    rhapi.ui.register_quickbutton(
        panel=PANEL_ID,
        name="local_voice_clear_cache",
        label="Clear TTS cache",
        function=clear_cache_callback,
    )
